# NUMPY

    - Library for mathematical calculations
    - Allow similar calculations as in Matlab
    - Efficient implementation of Arrays
    - Efficient linear algebra functions (matrix multiplications, inverses etc)
    - Basis for SciPy and Scikit Learn

In [1]:
l=[5,10,12]

In [2]:
import numpy as np

In [3]:
a=np.array(l)

In [4]:
print(a)
print(type(a))

[ 5 10 12]
<class 'numpy.ndarray'>


In [5]:
print(l)
print(type(l))

[5, 10, 12]
<class 'list'>


In [6]:
l.append(17)

In [7]:
l

[5, 10, 12, 17]

In [8]:
a.append(17)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [13]:
l+[5,6]

[5, 10, 12, 17, 5, 6]

In [14]:
a+[5,6]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
a1=a+5,6,7

In [12]:
type(a1)

tuple

In [13]:
a1

(array([10, 15, 17]), 6, 7)

In [15]:
np.array([3,4,7])+np.array([2,4,5])

array([ 5,  8, 12])

In [ ]:
# np.array and list multiplications

In [16]:
[2,3,4]*2

[2, 3, 4, 2, 3, 4]

In [17]:
L_times_two=[]
for n in [2,3,4]:
    L_times_two.append(n*2)

In [18]:
L_times_two

[4, 6, 8]

In [19]:
np.array([2,3,4])*2

array([4, 6, 8])

In [15]:
# If you have matrix it will do Matrix addition (element wise)

In [22]:
np1=np.array([2,4,3,4])

In [23]:
np1**2

array([ 4, 16,  9, 16])

In [21]:
L_times_two**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [24]:
print(np.sqrt(np1))
print(np.log(np1))
print(np.exp(np1))

[ 1.41421356  2.          1.73205081  2.        ]
[ 0.69314718  1.38629436  1.09861229  1.38629436]
[  7.3890561   54.59815003  20.08553692  54.59815003]


In [ ]:
# !!!!! If we want to do this with a list we have to use for loop

# Dot product 

In [25]:
A=np.array([2,3])
B=np.array([1,2])

8

In [28]:
A*B

array([2, 6])

In [34]:
np.sum(A*B)

8

In [36]:
(A*B).sum()

8

In [27]:
A.dot(B)

8

### Speed comparison

In [7]:
import numpy as np
x=np.random.randn(1000)
y=np.random.randn(1000)
T=100000

In [8]:
type(x)

numpy.ndarray

In [9]:
from datetime import datetime

In [10]:
def slow_dot(x,y):
    res=0
    for e,f in zip(x,y):
        res+=e*f
    return res
        

In [11]:
t0=datetime.now()
for t in range(T):
    slow_dot(x,y)
dt1=datetime.now()-t0

In [12]:
t0=datetime.now()
for t in range(T):
    np.dot(x,y)
dt2=datetime.now()-t0

In [14]:
dt1.total_seconds()/dt2.total_seconds()

251.0387392473518

# Vectors and Matrices 

In [15]:
M=np.array([[1,2],[3,4]])

In [16]:
L=[[1,2], [3,4]]

In [17]:
M

array([[1, 2],
       [3, 4]])

In [60]:
L[0]

[1, 2]

In [61]:
L[0][0]

1

In [ ]:
# Matrix type exists in numpy but it is not advisable to use it... Convert Matrix to arrray

In [63]:
M.T

array([[1, 3],
       [2, 4]])

### Generating matrices

In [64]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [65]:
np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [67]:
np.ones((10,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [68]:
np.random.random((10,10))

array([[ 0.21044378,  0.01063196,  0.76115413,  0.63266253,  0.69642844,
         0.28240681,  0.55746464,  0.45408203,  0.50950363,  0.83580032],
       [ 0.965414  ,  0.77032658,  0.84105614,  0.13375981,  0.40231181,
         0.90271239,  0.41727663,  0.46964   ,  0.22877201,  0.72274681],
       [ 0.88547396,  0.78778011,  0.77573974,  0.10070051,  0.44905712,
         0.4164198 ,  0.61953725,  0.49742213,  0.39848276,  0.87348275],
       [ 0.42965716,  0.02538346,  0.05740711,  0.42465474,  0.01083871,
         0.84369027,  0.1768477 ,  0.84271537,  0.85400264,  0.43213324],
       [ 0.0549521 ,  0.49716418,  0.53985896,  0.99894377,  0.45838963,
         0.4181305 ,  0.88069354,  0.85196061,  0.18574741,  0.32655344],
       [ 0.30628232,  0.16520648,  0.5248294 ,  0.87476682,  0.67624238,
         0.16842662,  0.09835042,  0.76281608,  0.33832046,  0.75497364],
       [ 0.26796897,  0.62751251,  0.29802449,  0.91984065,  0.60938724,
         0.35441458,  0.20180278,  0.94947646

### Matrix products (multiplication)

In [73]:
M*M

array([[ 1,  4],
       [ 9, 16]])

In [74]:
M.dot(M)

array([[ 7, 10],
       [15, 22]])

In [71]:
A

array([2, 3])

In [72]:
B

array([1, 2])