# NUMPY

    - Library for mathematical calculations
    - Allows similar calculations as in Matlab
    - Efficient implementation of Arrays (vectors)
    - Efficient linear algebra functions (matrix multiplications, inverses etc)
    - Basis for Pandas, Matplotlib, SciPy and Scikit Learn

##  Operations on lists (reminder)

In [24]:
my_list_1 = [2,4,5,8]
my_list_2 = [3,2,4,4]

In [25]:
my_list_1.append(1) # element is appended on the end of the list
my_list_1

[2, 4, 5, 8, 1]

In [26]:
my_list_1 + my_list_2 # all elements of my_list_2 are appended to the end of my_list_1

[2, 4, 5, 8, 1, 3, 2, 4, 4]

In [27]:
my_list_1 - my_list_2 # subtraction of lists is not supported

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [21]:
my_list_1.append(my_list_2) # my_list_2 is appended as last element of my_list_2

In [22]:
my_list_1

[2, 4, 5, 8, 1, [3, 2, 4, 4]]

## Numpy Arrays 

numpy.ndarray type represents vectors and allows mathematical vector operations:
- addition
- subtraction
- element wise multiplication
- dot product (vector multiplication or weighted sum)

In [2]:
import numpy as np

In [3]:
# Numpy array may be initialized from python list
my_list = [3,2,5,7,11]
my_np_array=np.array(my_list)
print(my_np_array)
print(type(my_np_array))

[ 3  2  5  7 11]
<class 'numpy.ndarray'>


In [12]:
# Lenth and shape of ndarrays
print('Length of array is {}'.format(len(my_np_array)))
print('Shape of array is {}'.format(my_np_array.shape))

Length of array is 5
Shape of array is (5,)


## Selection of elements

In [36]:
# selection by index
my_np_array[0]

3

Selection by slices (as with lists)

In [42]:

print(my_np_array[0:2])
print(my_np_array[::2]) # select all with step 2
print(my_np_array[[0,3]]) # select with list of indices
print(my_np_array[my_np_array>5]) # select by boolean condition

[3 2]
[ 3  5 11]
[3 7]
[ 7 11]


In [29]:
# elements may be removed with delete function
my_np_array = np.delete(my_np_array, [0,2])

array([2])

In [58]:
# insert function will update element on selected index (if exists) or add new element if not
print(np.insert(my_np_array, 5, 555))

print(np.append(my_np_array,2))
print(np.append(my_np_array,[2,6,77]))


[  3   2   5   7  11 555]
[ 3  2  5  7 11  2]
[ 3  2  5  7 11  2  6 77]


## Vector operations addition, multiplication, dot product etc.

In [18]:
my_npa_1 = np.array([2,3,3])
my_npa_2 = np.array([1,1])
my_npa_3 = np.array([1,1,2])


In [21]:
# Vector addition of nparrays is done elementwise ()
my_npa_1+my_npa_3 


array([3, 4, 5])

In [24]:
#Note that vector addition is different than list addition (in case of lists elements are inserted in list)
print(list(my_npa_1) + list(my_npa_3))
print(list(my_npa_1) +list(my_npa_2))

[2, 3, 3, 1, 1, 2]
[2, 3, 3, 1, 1]


In [20]:
# In contrast to lists, vector addition of unequal dimensions will throw an exception
my_npa_1+my_npa_2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### Vector scalar multiplication

In [30]:
# Scalar multiplication with numpy array gives correct 
print(my_npa_1)
print(my_npa_1*2)

[2 3 3]
[4 6 6]


In [32]:
# List multiplication copies the list and adds to the end of existing list
print([2,3,4]*2)
print([2,3,4]*3)

[2, 3, 4, 2, 3, 4]
[2, 3, 4, 2, 3, 4, 2, 3, 4]


In [12]:
# In order to do vector scalar multiplication with list it is necessary to use loops
L_times_two=[]
for n in [2,3,4]:
    L_times_two.append(n*2)
L_times_two

### Other element wise vector operations

In [35]:
print(my_npa_1**2)
print(np.sqrt(my_npa_1))
print(np.log(my_npa_1))
print(np.exp(my_npa_1))

# Note these operations would demand loops if lists were used

[4 9 9]
[ 1.41421356  1.73205081  1.73205081]
[ 0.69314718  1.09861229  1.09861229]
[  7.3890561   20.08553692  20.08553692]


In [15]:
# If you have matrix it will do Matrix addition (element wise)

### Dot product 

Dot product of two vectors is a scalar. It can be used and interpreted as weighted sum. 

numpy provides single function (np.dot()) to create dot product of two vectors

In [36]:
A=np.array([2,3])
B=np.array([1,2])

In [37]:
# dot product with numpy function
A.dot(B)

8

In [38]:
# dot product as sum of vector multiplication
A*B
np.sum(A*B)

8

In [34]:
# Alternative way to calculate dot product
(A*B).sum()

8

### Speed comparison

In [7]:
import numpy as np
x=np.random.randn(1000)
y=np.random.randn(1000)
T=100000

In [8]:
type(x)

numpy.ndarray

In [9]:
from datetime import datetime

In [10]:
def slow_dot(x,y):
    res=0
    for e,f in zip(x,y):
        res+=e*f
    return res
        

In [11]:
t0=datetime.now()
for t in range(T):
    slow_dot(x,y)
dt1=datetime.now()-t0

In [12]:
t0=datetime.now()
for t in range(T):
    np.dot(x,y)
dt2=datetime.now()-t0

In [14]:
dt1.total_seconds()/dt2.total_seconds()

251.0387392473518

# Numpy matrices

Numpy matices are in fact multidimensional numpy arrays, so data selection is very similar to 1-d arrays. Numpy allows linear algebra operations:
- Transposing
- Inverse
- Matrix vector multiplication, addition etc.
- Matrix Matrix multiplication, addition etc.

In [56]:
# Matrix as 2-d array
M=np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [57]:
M.shape

(2, 2)

In [58]:
# Matrix transpose
M.T

array([[1, 3],
       [2, 4]])

In [59]:
# Element vise matrix multiplication
M*M

array([[ 1,  4],
       [ 9, 16]])

In [53]:
# Matrix dot product
M.dot(M)

array([[ 7, 10],
       [15, 22]])

In [66]:
# Element wise Matrix vector multiplication
w = np.array([2, 4])
M*w

array([[ 2,  8],
       [ 6, 16]])

In [71]:
# Matrix vector dot product (weighted sum)
M.dot(w)

array([10, 22])

In [72]:
w.dot(M)

array([14, 20])

### Generating matrices

In [64]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [65]:
np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [67]:
np.ones((10,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [84]:
rand_matrix = np.random.random((4,4))
rand_matrix

array([[ 0.85775638,  0.5395841 ,  0.06883591,  0.95140825],
       [ 0.54123731,  0.3476222 ,  0.95604726,  0.44991128],
       [ 0.36796776,  0.20629987,  0.44548088,  0.98212165],
       [ 0.99048116,  0.57959152,  0.89926425,  0.85261749]])

In [85]:
rand_matrix = np.round(rand_matrix,2)*10
rand_matrix

array([[ 8.6,  5.4,  0.7,  9.5],
       [ 5.4,  3.5,  9.6,  4.5],
       [ 3.7,  2.1,  4.5,  9.8],
       [ 9.9,  5.8,  9. ,  8.5]])

In [87]:
rand_matrix[0:2, 2:]

array([[ 0.7,  9.5],
       [ 9.6,  4.5]])

In [88]:
# Adding rows or columns