# Data Mining and Machine Learning

In [39]:
from sklearn.ensemble import RandomForestClassifier
from pydataset import data
import numpy as np

In [3]:
data()

dataset_id  \
0            AirPassengers   
1                  BJsales   
2                      BOD   
3             Formaldehyde   
4             HairEyeColor   
5             InsectSprays   
6           JohnsonJohnson   
7                LakeHuron   
8         LifeCycleSavings   
9                     Nile   
10           OrchardSprays   
11             PlantGrowth   
12               Puromycin   
13                 Titanic   
14             ToothGrowth   
15           UCBAdmissions   
16          UKDriverDeaths   
17                   UKgas   
18             USAccDeaths   
19               USArrests   
20          USJudgeRatings   
21   USPersonalExpenditure   
22                VADeaths   
23                WWWusage   
24             WorldPhones   
25                airmiles   
26              airquality   
27                anscombe   
28                  attenu   
29                attitude   
30                 austres   
31                    cars   
32                chickwts   
33                     co2   
34                 crimtab   
35             discoveries   
36                   esoph   
37                    euro   
38                faithful   
39                  freeny   
40                  infert   
41                    iris   
42                 islands   
43                      lh   
44                 longley   
45                    lynx   
46                  morley   
47                  mtcars   
48                  nhtemp   
49                  nottem   
50                     npk   
51      occupationalStatus   
52                  precip   
53              presidents   
54                pressure   
55                  quakes   
56                   randu   
57                  rivers   
58                    rock   
59                   sleep   
60               stackloss   
61           sunspot.month   
62            sunspot.year   
63                sunspots   
64                   swiss   
65                treering   
66                   trees   
67                   uspop   
68                 volcano   
69              warpbreaks   
70                   women   
71                    acme   
72                    aids   
73               aircondit   
74              aircondit7   
75                    amis   
76                     aml   
77                 bigcity   
78                brambles   
79                 breslow   
80                 calcium   
81                    cane   
82              capability   
83                   catsM   
84                     cav   
..                     ...   
672               students   
673               suicides   
674             toothpaste   
675                 voting   
676                  water   
677             watervoles   
678                  waves   
679             weightgain   
680             womensrole   
681              Bechtoldt   
682            Bechtoldt.1   
683            Bechtoldt.2   
684                  Dwyer   
685                 Gleser   
686                Gorsuch   
687               Harman.5   
688               Harman.8   
689       Harman.political   
690              Holzinger   
691            Holzinger.9   
692                  Reise   
693                 Schmid   
694              Thurstone   
695           Thurstone.33   
696                 Tucker   
697                ability   
698                 affect   
699                    bfi   
700         bfi.dictionary   
701                   blot   
702                   burt   
703                 cities   
704                 cubits   
705                 cushny   
706                    epi   
707                epi.bfi   
708         epi.dictionary   
709                 galton   
710                heights   
711                 income   
712                iqitems   
713                    msq   
714                    neo   
715                   peas   
716                sat.act   
717          withinBetween   
718                  Bosco

In [40]:
iris=data('iris')

In [41]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [42]:
iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [43]:
X=iris.loc[: ,'Sepal.Length':'Petal.Length'] # Could be done with drop

In [44]:
y=iris.loc[: ,'Species']  # can be done without first argument

In [45]:
X[:10].count()

Sepal.Length    10
Sepal.Width     10
Petal.Length    10
dtype: int64

In [46]:
X[10:].count()

Sepal.Length    140
Sepal.Width     140
Petal.Length    140
dtype: int64

In [47]:
RF=RandomForestClassifier(n_estimators=10)

In [48]:
model=RF.fit(X,y)

In [49]:
type(model)

sklearn.ensemble.forest.RandomForestClassifier

In [50]:
predictions=model.predict(X)

Compare predictions with real labels

In [54]:
print(type(predictions))
print(type(y))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [55]:
y_real=np.array(y)

In [59]:
true_predicted=np.column_stack((y_real, predictions))

In [62]:
true_predicted[:,:]

array([['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setos

In [63]:
true_predicted.shape

(150, 2)

In [105]:
def split_train_test(df, test_percentage, shuffle=True):
    '''
    Splits Dataframe on train and test based on percentage
    Also shuffles data
    '''
    df=df.sample(frac=1)
    n=len(df)
    split=int(np.floor(n*test_percentage))
    test= df.iloc[:split,:]
    train=df.iloc[split:,:]
    return (train, test)
    
    

In [83]:
type(split_train_test(iris, 0.3))

tuple

In [106]:
train, test=split_train_test(iris, 0.3)

In [107]:
print(train.shape)
print(test.shape)
print(test.shape[0]/(train.shape[0]+test.shape[0]))

(105, 5)
(45, 5)
0.3


In [89]:
train.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [108]:
X_train=train.iloc[:, 0:4]
y_train=train.iloc[:,4]

In [111]:
len(X_train)

105

In [96]:
from sklearn.linear_model import LogisticRegression

In [99]:
LR= LogisticRegression()

In [112]:
model=LR.fit(X_train,y_train)

In [117]:
X_test=test.iloc[:,0:4]
y_test=test.iloc[:,4]

In [119]:
model.predict(X_test)

array(['versicolor', 'setosa', 'versicolor', 'setosa', 'setosa', 'setosa',
       'virginica', 'setosa', 'versicolor', 'virginica', 'setosa',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'setosa',
       'virginica', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'virginica', 'setosa', 'versicolor', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'virginica'], dtype=object)

### Real output from Classification algorithm are probabilities

In [123]:
model.predict_proba(X_test)[0:2,:]

array([[  1.21458133e-01,   7.10585868e-01,   1.67955999e-01],
       [  8.78707877e-01,   1.21261106e-01,   3.10167476e-05]])

In [124]:
np.set_printoptions(suppress=True)

In [160]:
model.predict_proba(X_test)[0:2,:]

array([[ 0.12145813,  0.71058587,  0.167956  ],
       [ 0.87870788,  0.12126111,  0.00003102]])

In [130]:
prediction_probs=model.predict_proba(X_test)[0:2,:]

In [ ]:
# Replacing values arr[arr > 255] = x

#### Using argmax we can take the largest probabilities

In [135]:
pred=np.argmax(model.predict_proba(X_test), axis=1)

#### And map them to labels

In [157]:
map_labels={0:'iris', 1:'Verti', 2:'Rerto'}

In [168]:
mapped=np.array([map_labels[x] for x in pred])

In [172]:
#np.column_stack((pred, mapped))

#### But predict function does that for us

In [174]:
predictions=model.predict(X_test)

## Evaluation measures (scoring)
       - http://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values

In [176]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [175]:
accuracy_score(y_test, predictions)

0.9555555555555556

In [177]:
confusion_matrix(y_test, predictions)

array([[19,  0,  0],
       [ 0, 15,  2],
       [ 0,  0,  9]])

# Task for today
    - Download Titanic Data from Kaggle
    - Read training data to Pandas Dataframe
    - Discuss which attributes are important for survival prediction
    - Shuffle training data
    - Split the data on predictors and label (X,y)
    - Try to fit Logistic regression on training data
    - Check types and remove all categorical features
    - Remove features that you do not consider important for prediction (i.e. ids, names)
    - Remove rows that have less than 200 features with NaNs in one column
    - Remove columns that have more than 500 Nans

In [195]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [246]:
train=pd.read_csv('~/Desktop/Titanic/train.csv')

### Check dataset

In [247]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [248]:
train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [249]:
categorical=train.select_dtypes(include=['object'])

In [250]:
categorical.describe()

Name   Sex  Ticket    Cabin Embarked
count                 891   891     891      204      889
unique                891     2     681      147        3
top     Coleff, Mr. Satio  male  347082  B96 B98        S
freq                    1   577       7        4      644

In [253]:
numerical.isnull().sum(axis=0)

PassengerId      0
Survived         0
Pclass           0
Age            177
SibSp            0
Parch            0
Fare             0
dtype: int64

In [251]:
numerical=train.select_dtypes(exclude=['object'])

In [254]:
numerical_withoutNan=numerical.dropna(how='any', subset=['Age'])

In [255]:
numerical_withoutNan.isnull().sum(axis=0)

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
dtype: int64

In [258]:
X=numerical_withoutNan.drop(['PassengerId', 'Survived'], axis=1)
# train=train.loc[:, train.columns != 'Cabin'] This can be alternative for one feature

In [261]:
y=numerical_withoutNan['Survived']

### Initialize and fit model 

In [265]:
LR = LogisticRegression()

In [266]:
lr_model=LR.fit(X,y)

In [267]:
lr_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [268]:
lr_model.coef_

array([[-0.95904749, -0.03717529, -0.26650099,  0.22893993,  0.00530298]])

In [269]:
X.columns

Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

### Read test data

test = pd.read_csv('~/Desktop/Titanic/test.csv')

#### We can see that there is no label (Survived)

In [319]:
test.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

#### There are Missing values in test, but also all the attributes (not only ones that are used for modelling)

In [320]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [321]:
lr_model.predict(test)

ValueError: could not convert string to float: 'C'

In [322]:
test_1=test[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']]

In [323]:
test_1.isnull().sum()

Pclass     0
Age       86
SibSp      0
Parch      0
Fare       1
dtype: int64

In [324]:
test_1.shape[0]

418

In [325]:
np.average(test_1['Age'])

nan

In [326]:
avg_age=np.average(test_1['Age'].dropna())

In [315]:
test_1.Age.fillna(avg_age, inplace=True)

/Users/user/anaconda/lib/python3.5/site-packages/pandas/core/generic.py:2862: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [312]:
test_1['Age']=filled

/Users/user/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [328]:
test_1.Age.replace(np.NaN, avg_age, inplace=True)

/Users/user/anaconda/lib/python3.5/site-packages/pandas/core/generic.py:3117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [329]:
test_1.isnull().sum()

Pclass    0
Age       0
SibSp     0
Parch     0
Fare      1
dtype: int64

In [333]:
test_1.Fare.dropna(axis=0, inplace=True)

/Users/user/anaconda/lib/python3.5/site-packages/pandas/core/series.py:2546: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(result)


In [332]:
test_1.isnull().sum()

Pclass    0
Age       0
SibSp     0
Parch     0
Fare      0
dtype: int64